### PR TITLE
#95 cache

### PR DESCRIPTION
**Pull request by Lukeslux**
Uses the sessionStorage to cache articleLinks, will simply retrieve articles if not cached yet or caching is not possible (old browser, or caching disabled).

### CODE REVIEW

**Comment by mircealungu** [comment]
Do you think it would make sense to ensure that there's always documentation submitted together with the pull request. Especially if it's a new feature, I'd love to have taht!!!

**Comment by Lukeslux** [comment]
Should be implemented in the associated pull-request now.

**Comment by Lukeslux** [comment]
Yes, good idea!

**Comment by Lukeslux** [comment]
Would be cool if travis would check for documentation coverage as well.

**Comment by mircealungu** [comment]
Eheh. We said we'd do that by the end of the thesis, and we'll do it :)

**Pull request merged**
